INSERT INTO PRODUCTS (PRODUCTID,DESCRIPTION,PRICE) VALUES (1,'BASKET',100);
INSERT INTO PRODUCTS (PRODUCTID,DESCRIPTION,PRICE) VALUES (2,'BOOK',100);
INSERT INTO PRODUCTS (PRODUCTID,DESCRIPTION,PRICE) VALUES (3,'PEN',100);
INSERT INTO PRODUCTS (PRODUCTID,DESCRIPTION,PRICE) VALUES (4,'PENCIL',100);
INSERT INTO PRODUCTS (PRODUCTID,DESCRIPTION,PRICE) VALUES (5,'BALL',100);