spring:
  application:
    name: lbeureka

server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  instance:
    hostname: eureka-service
  server:
    waitTimeInMsWhenSyncEmpty: 0

